version: "3.8"
services:
  api:
    container_name: api
    image: nest_crud-api
    # build: 
    #   dockerfile: Dockerfile
    #   context: .
    depends_on:
      - redis
      - postgres
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      AT_SECRET: ${AT_SECRET}
      RT_SECRET: ${RT_SECRET}
      PORT: 3000
    ports:
      - "3000:3000"

  redis:
    container_name: cache
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

  postgres:
    image: postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

volumes:
  redis:
    driver: local
  docker-nest-postgres: